/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreditCardAccount : IEquatable<CreditCardAccount>
    { 
        /// <summary>
        /// The minimum payment amount due for the next card payment
        /// </summary>
        /// <value>The minimum payment amount due for the next card payment</value>
        [Required]
        [DataMember(Name="minPaymentAmount")]
        public string MinPaymentAmount { get; set; }

        /// <summary>
        /// The amount due for the next card payment
        /// </summary>
        /// <value>The amount due for the next card payment</value>
        [Required]
        [DataMember(Name="paymentDueAmount")]
        public string PaymentDueAmount { get; set; }

        /// <summary>
        /// If absent assumes AUD
        /// </summary>
        /// <value>If absent assumes AUD</value>
        [DataMember(Name="paymentCurrency")]
        public string PaymentCurrency { get; set; }

        /// <summary>
        /// Date that the next payment for the card is due
        /// </summary>
        /// <value>Date that the next payment for the card is due</value>
        [Required]
        [DataMember(Name="paymentDueDate")]
        public string PaymentDueDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditCardAccount {\n");
            sb.Append("  MinPaymentAmount: ").Append(MinPaymentAmount).Append("\n");
            sb.Append("  PaymentDueAmount: ").Append(PaymentDueAmount).Append("\n");
            sb.Append("  PaymentCurrency: ").Append(PaymentCurrency).Append("\n");
            sb.Append("  PaymentDueDate: ").Append(PaymentDueDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreditCardAccount)obj);
        }

        /// <summary>
        /// Returns true if CreditCardAccount instances are equal
        /// </summary>
        /// <param name="other">Instance of CreditCardAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditCardAccount other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MinPaymentAmount == other.MinPaymentAmount ||
                    MinPaymentAmount != null &&
                    MinPaymentAmount.Equals(other.MinPaymentAmount)
                ) && 
                (
                    PaymentDueAmount == other.PaymentDueAmount ||
                    PaymentDueAmount != null &&
                    PaymentDueAmount.Equals(other.PaymentDueAmount)
                ) && 
                (
                    PaymentCurrency == other.PaymentCurrency ||
                    PaymentCurrency != null &&
                    PaymentCurrency.Equals(other.PaymentCurrency)
                ) && 
                (
                    PaymentDueDate == other.PaymentDueDate ||
                    PaymentDueDate != null &&
                    PaymentDueDate.Equals(other.PaymentDueDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MinPaymentAmount != null)
                    hashCode = hashCode * 59 + MinPaymentAmount.GetHashCode();
                    if (PaymentDueAmount != null)
                    hashCode = hashCode * 59 + PaymentDueAmount.GetHashCode();
                    if (PaymentCurrency != null)
                    hashCode = hashCode * 59 + PaymentCurrency.GetHashCode();
                    if (PaymentDueDate != null)
                    hashCode = hashCode * 59 + PaymentDueDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreditCardAccount left, CreditCardAccount right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreditCardAccount left, CreditCardAccount right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
