/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DepositBalance : IEquatable<DepositBalance>
    { 
        /// <summary>
        /// Gets or Sets CurrentBalance
        /// </summary>
        [Required]
        [DataMember(Name="currentBalance")]
        public CurrencyAmount CurrentBalance { get; set; }

        /// <summary>
        /// Gets or Sets AvailableBalance
        /// </summary>
        [Required]
        [DataMember(Name="availableBalance")]
        public CurrencyAmount AvailableBalance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DepositBalance {\n");
            sb.Append("  CurrentBalance: ").Append(CurrentBalance).Append("\n");
            sb.Append("  AvailableBalance: ").Append(AvailableBalance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DepositBalance)obj);
        }

        /// <summary>
        /// Returns true if DepositBalance instances are equal
        /// </summary>
        /// <param name="other">Instance of DepositBalance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DepositBalance other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CurrentBalance == other.CurrentBalance ||
                    CurrentBalance != null &&
                    CurrentBalance.Equals(other.CurrentBalance)
                ) && 
                (
                    AvailableBalance == other.AvailableBalance ||
                    AvailableBalance != null &&
                    AvailableBalance.Equals(other.AvailableBalance)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CurrentBalance != null)
                    hashCode = hashCode * 59 + CurrentBalance.GetHashCode();
                    if (AvailableBalance != null)
                    hashCode = hashCode * 59 + AvailableBalance.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DepositBalance left, DepositBalance right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DepositBalance left, DepositBalance right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
