/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DomesticPayeeAccount : IEquatable<DomesticPayeeAccount>
    { 
        /// <summary>
        /// Name of the account to pay to
        /// </summary>
        /// <value>Name of the account to pay to</value>
        [Required]
        [DataMember(Name="accountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// BSB of the account to pay to
        /// </summary>
        /// <value>BSB of the account to pay to</value>
        [Required]
        [DataMember(Name="bsb")]
        public string Bsb { get; set; }

        /// <summary>
        /// Number of the account to pay to
        /// </summary>
        /// <value>Number of the account to pay to</value>
        [Required]
        [DataMember(Name="accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DomesticPayeeAccount {\n");
            sb.Append("  AccountName: ").Append(AccountName).Append("\n");
            sb.Append("  Bsb: ").Append(Bsb).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DomesticPayeeAccount)obj);
        }

        /// <summary>
        /// Returns true if DomesticPayeeAccount instances are equal
        /// </summary>
        /// <param name="other">Instance of DomesticPayeeAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DomesticPayeeAccount other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AccountName == other.AccountName ||
                    AccountName != null &&
                    AccountName.Equals(other.AccountName)
                ) && 
                (
                    Bsb == other.Bsb ||
                    Bsb != null &&
                    Bsb.Equals(other.Bsb)
                ) && 
                (
                    AccountNumber == other.AccountNumber ||
                    AccountNumber != null &&
                    AccountNumber.Equals(other.AccountNumber)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AccountName != null)
                    hashCode = hashCode * 59 + AccountName.GetHashCode();
                    if (Bsb != null)
                    hashCode = hashCode * 59 + Bsb.GetHashCode();
                    if (AccountNumber != null)
                    hashCode = hashCode * 59 + AccountNumber.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DomesticPayeeAccount left, DomesticPayeeAccount right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DomesticPayeeAccount left, DomesticPayeeAccount right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
