/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
        /// <summary>
        /// The list of available product categories for categorising products and accounts
        /// </summary>
        /// <value>The list of available product categories for categorising products and accounts</value>
        
        public enum EnumProductCategory
        {
            /// <summary>
            /// Enum PERSATCALLDEPOSITSEnum for PERS_AT_CALL_DEPOSITS
            /// </summary>
            
            PERSATCALLDEPOSITSEnum,            /// <summary>
            /// Enum BUSATCALLDEPOSITSEnum for BUS_AT_CALL_DEPOSITS
            /// </summary>
            
            BUSATCALLDEPOSITSEnum,            /// <summary>
            /// Enum TERMDEPOSITSEnum for TERM_DEPOSITS
            /// </summary>
            
            TERMDEPOSITSEnum,            /// <summary>
            /// Enum RESIDENTIALMORTGAGESEnum for RESIDENTIAL_MORTGAGES
            /// </summary>
            
            RESIDENTIALMORTGAGESEnum,            /// <summary>
            /// Enum PERSCREDANDCHRGCARDSEnum for PERS_CRED_AND_CHRG_CARDS
            /// </summary>
            
            PERSCREDANDCHRGCARDSEnum,            /// <summary>
            /// Enum BUSCREDANDCHRGCARDSEnum for BUS_CRED_AND_CHRG_CARDS
            /// </summary>
            
            BUSCREDANDCHRGCARDSEnum,            /// <summary>
            /// Enum PERSLOANSEnum for PERS_LOANS
            /// </summary>
            
            PERSLOANSEnum,            /// <summary>
            /// Enum PERSLEASINGEnum for PERS_LEASING
            /// </summary>
            
            PERSLEASINGEnum,            /// <summary>
            /// Enum BUSLEASINGEnum for BUS_LEASING
            /// </summary>
            
            BUSLEASINGEnum,            /// <summary>
            /// Enum TRADEFINANCEEnum for TRADE_FINANCE
            /// </summary>
            
            TRADEFINANCEEnum,            /// <summary>
            /// Enum PERSOVERDRAFTEnum for PERS_OVERDRAFT
            /// </summary>
            
            PERSOVERDRAFTEnum,            /// <summary>
            /// Enum BUSOVERDRAFTEnum for BUS_OVERDRAFT
            /// </summary>
            
            BUSOVERDRAFTEnum,            /// <summary>
            /// Enum BUSLOANSEnum for BUS_LOANS
            /// </summary>
            
            BUSLOANSEnum,            /// <summary>
            /// Enum FOREIGNCURRATCALLDEPOSITSEnum for FOREIGN_CURR_AT_CALL_DEPOSITS
            /// </summary>
            
            FOREIGNCURRATCALLDEPOSITSEnum,            /// <summary>
            /// Enum FOREIGNCURRTERMDEPOSITSEnum for FOREIGN_CURR_TERM_DEPOSITS
            /// </summary>
            
            FOREIGNCURRTERMDEPOSITSEnum,            /// <summary>
            /// Enum FOREIGNCURRLOANEnum for FOREIGN_CURR_LOAN
            /// </summary>
            
            FOREIGNCURRLOANEnum,            /// <summary>
            /// Enum FOREIGNCURRRENCTOVERDRAFTEnum for FOREIGN_CURRRENCT_OVERDRAFT
            /// </summary>
            
            FOREIGNCURRRENCTOVERDRAFTEnum,            /// <summary>
            /// Enum TRAVELCARDEnum for TRAVEL_CARD
            /// </summary>
            
            TRAVELCARDEnum
        }
}
