/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InternationalPayee : IEquatable<InternationalPayee>
    { 
        /// <summary>
        /// Gets or Sets BeneficiaryDetails
        /// </summary>
        [Required]
        [DataMember(Name="beneficiaryDetails")]
        public InternationalPayeeBeneficiaryDetails BeneficiaryDetails { get; set; }

        /// <summary>
        /// Gets or Sets BankDetails
        /// </summary>
        [Required]
        [DataMember(Name="bankDetails")]
        public InternationalPayeeBankDetails BankDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InternationalPayee {\n");
            sb.Append("  BeneficiaryDetails: ").Append(BeneficiaryDetails).Append("\n");
            sb.Append("  BankDetails: ").Append(BankDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InternationalPayee)obj);
        }

        /// <summary>
        /// Returns true if InternationalPayee instances are equal
        /// </summary>
        /// <param name="other">Instance of InternationalPayee to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InternationalPayee other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BeneficiaryDetails == other.BeneficiaryDetails ||
                    BeneficiaryDetails != null &&
                    BeneficiaryDetails.Equals(other.BeneficiaryDetails)
                ) && 
                (
                    BankDetails == other.BankDetails ||
                    BankDetails != null &&
                    BankDetails.Equals(other.BankDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BeneficiaryDetails != null)
                    hashCode = hashCode * 59 + BeneficiaryDetails.GetHashCode();
                    if (BankDetails != null)
                    hashCode = hashCode * 59 + BankDetails.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InternationalPayee left, InternationalPayee right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InternationalPayee left, InternationalPayee right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
