/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductEligibility : IEquatable<ProductEligibility>
    { 
        /// <summary>
        /// The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning
        /// </summary>
        /// <value>The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum EligibilityTypeEnum
        {
            /// <summary>
            /// Enum BUSINESSEnum for BUSINESS
            /// </summary>
            [EnumMember(Value = "BUSINESS")]
            BUSINESSEnum = 1,            /// <summary>
            /// Enum PENSIONRECIPIENTEnum for PENSION_RECIPIENT
            /// </summary>
            [EnumMember(Value = "PENSION_RECIPIENT")]
            PENSIONRECIPIENTEnum = 2,            /// <summary>
            /// Enum MINAGEEnum for MIN_AGE
            /// </summary>
            [EnumMember(Value = "MIN_AGE")]
            MINAGEEnum = 3,            /// <summary>
            /// Enum MAXAGEEnum for MAX_AGE
            /// </summary>
            [EnumMember(Value = "MAX_AGE")]
            MAXAGEEnum = 4,            /// <summary>
            /// Enum MININCOMEEnum for MIN_INCOME
            /// </summary>
            [EnumMember(Value = "MIN_INCOME")]
            MININCOMEEnum = 5,            /// <summary>
            /// Enum MINTURNOVEREnum for MIN_TURNOVER
            /// </summary>
            [EnumMember(Value = "MIN_TURNOVER")]
            MINTURNOVEREnum = 6,            /// <summary>
            /// Enum STAFFEnum for STAFF
            /// </summary>
            [EnumMember(Value = "STAFF")]
            STAFFEnum = 7,            /// <summary>
            /// Enum STUDENTEnum for STUDENT
            /// </summary>
            [EnumMember(Value = "STUDENT")]
            STUDENTEnum = 8,            /// <summary>
            /// Enum EMPLOYMENTSTATUSEnum for EMPLOYMENT_STATUS
            /// </summary>
            [EnumMember(Value = "EMPLOYMENT_STATUS")]
            EMPLOYMENTSTATUSEnum = 9,            /// <summary>
            /// Enum RESIDENCYSTATUSEnum for RESIDENCY_STATUS
            /// </summary>
            [EnumMember(Value = "RESIDENCY_STATUS")]
            RESIDENCYSTATUSEnum = 10,            /// <summary>
            /// Enum OTHEREnum for OTHER
            /// </summary>
            [EnumMember(Value = "OTHER")]
            OTHEREnum = 11
        }

        /// <summary>
        /// The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning
        /// </summary>
        /// <value>The type of eligibility criteria described.  See the next section for an overview of valid values and their meaning</value>
        [Required]
        [DataMember(Name="eligibilityType")]
        public EligibilityTypeEnum? EligibilityType { get; set; }

        /// <summary>
        /// Generic field containing additional information relevant to the eligibilityType specified.  Whether mandatory or not is dependent on the value of eligibilityType
        /// </summary>
        /// <value>Generic field containing additional information relevant to the eligibilityType specified.  Whether mandatory or not is dependent on the value of eligibilityType</value>
        [DataMember(Name="additionalValue")]
        public string AdditionalValue { get; set; }

        /// <summary>
        /// Display text providing more information on the eligibility criteria. Mandatory if the eligibilityType field is set to OTHER
        /// </summary>
        /// <value>Display text providing more information on the eligibility criteria. Mandatory if the eligibilityType field is set to OTHER</value>
        [DataMember(Name="additionalInfo")]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// Link to a web page with more information on this eligibility criteria
        /// </summary>
        /// <value>Link to a web page with more information on this eligibility criteria</value>
        [DataMember(Name="additionalInfoUri")]
        public string AdditionalInfoUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductEligibility {\n");
            sb.Append("  EligibilityType: ").Append(EligibilityType).Append("\n");
            sb.Append("  AdditionalValue: ").Append(AdditionalValue).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("  AdditionalInfoUri: ").Append(AdditionalInfoUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductEligibility)obj);
        }

        /// <summary>
        /// Returns true if ProductEligibility instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductEligibility to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductEligibility other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EligibilityType == other.EligibilityType ||
                    EligibilityType != null &&
                    EligibilityType.Equals(other.EligibilityType)
                ) && 
                (
                    AdditionalValue == other.AdditionalValue ||
                    AdditionalValue != null &&
                    AdditionalValue.Equals(other.AdditionalValue)
                ) && 
                (
                    AdditionalInfo == other.AdditionalInfo ||
                    AdditionalInfo != null &&
                    AdditionalInfo.Equals(other.AdditionalInfo)
                ) && 
                (
                    AdditionalInfoUri == other.AdditionalInfoUri ||
                    AdditionalInfoUri != null &&
                    AdditionalInfoUri.Equals(other.AdditionalInfoUri)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EligibilityType != null)
                    hashCode = hashCode * 59 + EligibilityType.GetHashCode();
                    if (AdditionalValue != null)
                    hashCode = hashCode * 59 + AdditionalValue.GetHashCode();
                    if (AdditionalInfo != null)
                    hashCode = hashCode * 59 + AdditionalInfo.GetHashCode();
                    if (AdditionalInfoUri != null)
                    hashCode = hashCode * 59 + AdditionalInfoUri.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductEligibility left, ProductEligibility right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductEligibility left, ProductEligibility right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
