/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductConstraints : IEquatable<ProductConstraints>
    { 
        /// <summary>
        /// The type of constraint described.  See the next section for an overview of valid values and their meaning
        /// </summary>
        /// <value>The type of constraint described.  See the next section for an overview of valid values and their meaning</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ConstraintTypeEnum
        {
            /// <summary>
            /// Enum MINBALANCEEnum for MIN_BALANCE
            /// </summary>
            [EnumMember(Value = "MIN_BALANCE")]
            MINBALANCEEnum = 1,            /// <summary>
            /// Enum OPENINGBALANCEEnum for OPENING_BALANCE
            /// </summary>
            [EnumMember(Value = "OPENING_BALANCE")]
            OPENINGBALANCEEnum = 2,            /// <summary>
            /// Enum MAXLIMITEnum for MAX_LIMIT
            /// </summary>
            [EnumMember(Value = "MAX_LIMIT")]
            MAXLIMITEnum = 3,            /// <summary>
            /// Enum MINLIMITEnum for MIN_LIMIT
            /// </summary>
            [EnumMember(Value = "MIN_LIMIT")]
            MINLIMITEnum = 4
        }

        /// <summary>
        /// The type of constraint described.  See the next section for an overview of valid values and their meaning
        /// </summary>
        /// <value>The type of constraint described.  See the next section for an overview of valid values and their meaning</value>
        [Required]
        [DataMember(Name="constraintType")]
        public ConstraintTypeEnum? ConstraintType { get; set; }

        /// <summary>
        /// Generic field containing additional information relevant to the constraintType specified.  Whether mandatory or not is dependent on the value of constraintType
        /// </summary>
        /// <value>Generic field containing additional information relevant to the constraintType specified.  Whether mandatory or not is dependent on the value of constraintType</value>
        [DataMember(Name="additionalValue")]
        public string AdditionalValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductConstraints {\n");
            sb.Append("  ConstraintType: ").Append(ConstraintType).Append("\n");
            sb.Append("  AdditionalValue: ").Append(AdditionalValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductConstraints)obj);
        }

        /// <summary>
        /// Returns true if ProductConstraints instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductConstraints to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductConstraints other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ConstraintType == other.ConstraintType ||
                    ConstraintType != null &&
                    ConstraintType.Equals(other.ConstraintType)
                ) && 
                (
                    AdditionalValue == other.AdditionalValue ||
                    AdditionalValue != null &&
                    AdditionalValue.Equals(other.AdditionalValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ConstraintType != null)
                    hashCode = hashCode * 59 + ConstraintType.GetHashCode();
                    if (AdditionalValue != null)
                    hashCode = hashCode * 59 + AdditionalValue.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductConstraints left, ProductConstraints right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductConstraints left, ProductConstraints right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
