/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace OpenBanking.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ResponseCommonCustomerDetailedData : IEquatable<ResponseCommonCustomerDetailedData>
    { 
        /// <summary>
        /// The type of customer object that is present
        /// </summary>
        /// <value>The type of customer object that is present</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CustomerUTypeEnum
        {
            /// <summary>
            /// Enum PersonEnum for person
            /// </summary>
            [EnumMember(Value = "person")]
            PersonEnum = 1,            /// <summary>
            /// Enum OrganisationEnum for organisation
            /// </summary>
            [EnumMember(Value = "organisation")]
            OrganisationEnum = 2
        }

        /// <summary>
        /// The type of customer object that is present
        /// </summary>
        /// <value>The type of customer object that is present</value>
        [Required]
        [DataMember(Name="customerUType")]
        public CustomerUTypeEnum? CustomerUType { get; set; }

        /// <summary>
        /// Gets or Sets Person
        /// </summary>
        [DataMember(Name="person")]
        public PersonDetail Person { get; set; }

        /// <summary>
        /// Gets or Sets Organisation
        /// </summary>
        [DataMember(Name="organisation")]
        public OrganisationDetail Organisation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseCommonCustomerDetailedData {\n");
            sb.Append("  CustomerUType: ").Append(CustomerUType).Append("\n");
            sb.Append("  Person: ").Append(Person).Append("\n");
            sb.Append("  Organisation: ").Append(Organisation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ResponseCommonCustomerDetailedData)obj);
        }

        /// <summary>
        /// Returns true if ResponseCommonCustomerDetailedData instances are equal
        /// </summary>
        /// <param name="other">Instance of ResponseCommonCustomerDetailedData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseCommonCustomerDetailedData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CustomerUType == other.CustomerUType ||
                    CustomerUType != null &&
                    CustomerUType.Equals(other.CustomerUType)
                ) && 
                (
                    Person == other.Person ||
                    Person != null &&
                    Person.Equals(other.Person)
                ) && 
                (
                    Organisation == other.Organisation ||
                    Organisation != null &&
                    Organisation.Equals(other.Organisation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CustomerUType != null)
                    hashCode = hashCode * 59 + CustomerUType.GetHashCode();
                    if (Person != null)
                    hashCode = hashCode * 59 + Person.GetHashCode();
                    if (Organisation != null)
                    hashCode = hashCode * 59 + Organisation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ResponseCommonCustomerDetailedData left, ResponseCommonCustomerDetailedData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ResponseCommonCustomerDetailedData left, ResponseCommonCustomerDetailedData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
